spring.application.name=ColabManager

# Configura��o do banco de dados PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/ColabManager
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# Configura��o de JPA para PostgreSQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Configura��es espec�ficas do PostgreSQL
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false

# Outras configura��es
spring.sql.init.mode=always